export const QUOTES = [
  { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "Study while others are sleeping; work while others are loafing; prepare while others are playing; and dream while others are wishing.", author: "William A. Ward" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { text: "The beautiful thing about learning is that no one can take it away from you.", author: "B.B. King" },
  { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
  { text: "You do not rise to the level of your goals. You fall to the level of your systems.", author: "James Clear" },
  { text: "Motivation gets you going, but discipline keeps you growing.", author: "John C. Maxwell" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Strive for progress, not perfection.", author: "Unknown" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { text: "Success doesn't come from what you do occasionally, but what you do consistently.", author: "Marie Forleo" },
  { text: "Dream big. Start small. Act now.", author: "Robin Sharma" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "Learn as if you will live forever, live as if you will die tomorrow.", author: "Mahatma Gandhi" },
  { text: "Reading is to the mind what exercise is to the body.", author: "Joseph Addison" },
  { text: "The more that you read, the more things you will know.", author: "Dr. Seuss" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "The only way to learn mathematics is to do mathematics.", author: "Paul Halmos" },
  { text: "Every accomplishment starts with the decision to try.", author: "John F. Kennedy" },
  { text: "Great things are done by a series of small things brought together.", author: "Vincent van Gogh" },
  { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
  { text: "A day without sunshine is like, you know, night.", author: "Steve Martin" },
  { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
  { text: "Small deeds done are better than great deeds planned.", author: "Peter Marshall" },
  { text: "A little progress each day adds up to big results.", author: "Satya Nani" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "If people knew how hard I worked to get my mastery, it wouldn't seem so wonderful at all.", author: "Michelangelo" },
  { text: "Do not wait; the time will never be 'just right.' Start where you stand.", author: "Napoleon Hill" },
  { text: "Talent is cheaper than table salt. What separates the talented individual from the successful one is a lot of hard work.", author: "Stephen King" },
  { text: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "Mistakes are proof that you are trying.", author: "Unknown" },
  { text: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
  { text: "Little by little, one travels far.", author: "J.R.R. Tolkien" },
  { text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { text: "Fortune favors the bold.", author: "Virgil" },
  { text: "Do something today that your future self will thank you for.", author: "Sean Patrick Flanery" },
  { text: "Hard choices, easy life. Easy choices, hard life.", author: "Jerzy Gregorek" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Unknown" },
  { text: "Fall seven times, stand up eight.", author: "Unknown" },
  { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { text: "Every strike brings me closer to the next home run.", author: "Babe Ruth" },
  { text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi" },
  { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
  { text: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "Tough times never last, but tough people do.", author: "Robert H. Schuller" },
  { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
  { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
  { text: "An unexamined life is not worth living.", author: "Socrates" },
  { text: "The best way out is always through.", author: "Robert Frost" },
  { text: "We are what we pretend to be, so we must be careful about what we pretend to be.", author: "Kurt Vonnegut" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { text: "Dreams are not those that we see in our sleep; they should be the ones that never let us sleep.", author: "APJ Abdul Kalam" },
  { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { text: "It is not the mountain we conquer, but ourselves.", author: "Edmund Hillary" },
  { text: "Well begun is half done.", author: "Ancient Greek proverb" },
  { text: "The gem cannot be polished without friction, nor man perfected without trials.", author: "Chinese proverb" },
  { text: "Learning is not attained by chance; it must be sought for with ardor and attended to with diligence.", author: "Abigail Adams" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "There is no substitute for hard work.", author: "Thomas Edison" },
  { text: "He will wipe away every tear from their eyes, and death shall be no more, neither shall there be mourning, nor crying, nor pain anymore, for the former things have passed away", author: "Revelation 21:4" },
  { text: "Systems are best for making progress.", author: "James Clear • Atomic Habits" },
  { text: "Habits are the compound interest of self-improvement.", author: "James Clear • Atomic Habits" },
  { text: "Be more concerned with your current trajectory than your current results.", author: "James Clear • Atomic Habits" },
  { text: "Start with the end in mind.", author: "Stephen R. Covey • The 7 Habits" },
  { text: "And we know that for those who love God all things work together for good, for those who are called according to his purpose.", author: "Romans 8:28"},
  { text: "Put first things first.", author: "Stephen R. Covey • The 7 Habits" },
  { text: "Even to your old age and gray hairs I am he, I am he who will sustain you. I have made you and I will carry you; I will sustain you and I will rescue you.", author: "Isaiah 46:4" },
  { text: "Seek first to understand, then to be understood.", author: "Stephen R. Covey • The 7 Habits" },
  { text: "Keep the main thing the main thing.", author: "Stephen R. Covey • The 7 Habits" },
  { text: "Character is not what we have done, but rather who we are.", author: "Bill Hybels • Who You Are When No One’s Looking" },
  { text: "If 50 million people say something foolish, it is still foolish.", author: "Rolf Dobelli • The Art of Thinking Clearly" },
  { text: "Facts do not cease to exist because they are ignored.", author: "Rolf Dobelli • The Art of Thinking Clearly" },
  { text: "Every action you take is a vote for the person you wish to become.", author: "James Clear • Atomic Habits" },
  { text: "Shoot for the moon. Even if you miss, you'll land among the stars.", author: "Norman Vincent Peale" },
  { text: "This is the day that the Lord has made; let us rejoice and be glad in it.", author: "Psalm 118:24" },
]

export function quoteOfTheDay() {
  const msPerDay = 24 * 60 * 60 * 1000;
  const midnight = new Date().setHours(0, 0, 0, 0)
  const day = Math.floor(midnight/ msPerDay);
  const result = QUOTES[day % QUOTES.length]
  
  return result
}